/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TeamsComponent {
    }
}
declare global {
    interface HTMLTeamsComponentElement extends Components.TeamsComponent, HTMLStencilElement {
    }
    var HTMLTeamsComponentElement: {
        prototype: HTMLTeamsComponentElement;
        new (): HTMLTeamsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "teams-component": HTMLTeamsComponentElement;
    }
}
declare namespace LocalJSX {
    interface TeamsComponent {
    }
    interface IntrinsicElements {
        "teams-component": TeamsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "teams-component": LocalJSX.IntrinsicElements["teams-component"] & JSXBase.HTMLAttributes<HTMLTeamsComponentElement>;
        }
    }
}
